apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emissary-ingress
  namespace: ingress
spec:
  project: default
  source:
    chart: emissary-ingress
    helm:
      parameters:
      - name: dashboard.enabled
        value: "true"
      - name: dashboard.service.port
        value: 3200
    repoURL: https://app.getambassador.io
    targetRevision: 2.14.0
    helm:
      releaseName: emissary-ingress
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress