apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emissary-ingress
  namespace: emissary
spec:
  project: default
  source:
    chart: emissary-ingress
    repoURL: https://app.getambassador.io
    targetRevision: 2.14.0
    helm:
      releaseName: emissary-ingress
  destination:
    server: "https://kubernetes.default.svc"
    namespace: emissary